import { useState } from 'react'
import { useCatalog } from './CatalogStore'
import { useOperations } from './OperationsStore'
import { dateTime, methods, money, type BusinessSettings, type PackageSale, type ServicePackage } from './operations'
import { EmptyState, Modal, Page } from './ManagementPages'

export function Packages() {
  const { data, run, busy, error } = useOperations()
  const { services } = useCatalog()
  const [view, setView] = useState<'packages' | 'sales'>('packages')
  const [draft, setDraft] = useState<ServicePackage | null>(null)
  const [quantities, setQuantities] = useState<Record<string, number>>({})
  const [saleOpen, setSaleOpen] = useState(false)
  const [salePackage, setSalePackage] = useState('')
  const [saleCustomer, setSaleCustomer] = useState('')
  const [saleMethod, setSaleMethod] = useState('pix')
  const [redeem, setRedeem] = useState<PackageSale | null>(null)
  const [redeemService, setRedeemService] = useState('')
  const activeCash = data.sessions.some(session => !session.closed_at)
  const fresh: ServicePackage = { id: '', name: '', description: '', price_cents: 0, active: true, created_at: '', items: [] }
  const editPackage = (item: ServicePackage) => { setDraft({ ...item }); setQuantities(Object.fromEntries(item.items.map(service => [service.service_id, service.quantity]))) }
  const openSale = (packageId = '') => { setSalePackage(packageId); setSaleCustomer(''); setSaleMethod('pix'); setSaleOpen(true) }
  return <Page title="Pacotes" action={<div className="row-actions"><button className="outline" onClick={() => openSale()}>Vender</button><button className="primary" onClick={() => editPackage(fresh)}>Novo pacote</button></div>}>
    <div className="command-filters"><button className={view === 'packages' ? 'active' : ''} onClick={() => setView('packages')}>Pacotes <span>{data.packages.length}</span></button><button className={view === 'sales' ? 'active' : ''} onClick={() => setView('sales')}>Vendidos <span>{data.packageSales.length}</span></button></div>
    {view === 'packages' ? <section className="package-grid">{data.packages.map(item => <article className="package-card" key={item.id}><div><span className={`status ${item.active ? 'positive' : 'muted'}`}>{item.active ? 'Ativo' : 'Pausado'}</span><h3>{item.name}</h3><strong>{money(item.price_cents)}</strong></div><ul>{item.items.map(service => <li key={service.service_id}>{service.quantity}× {service.service_name}</li>)}</ul><button className="outline small" onClick={() => editPackage(item)}>Editar</button></article>)}{!data.packages.length && <EmptyState>Nenhum pacote cadastrado.</EmptyState>}</section> : <section className="panel operation-panel package-sales">{data.packageSales.map(sale => { const remaining = sale.balances.reduce((sum, item) => sum + item.remaining, 0); return <div className="record-row" key={sale.id}><div><strong>{sale.customer_name}</strong><p>{sale.package_name} · {dateTime(sale.sold_at)}</p><small>{remaining} sessões restantes · {methods[sale.method]}</small></div><strong>{money(sale.amount_cents)}</strong><button className="outline small" disabled={sale.status !== 'active' || remaining === 0} onClick={() => { setRedeem(sale); setRedeemService('') }}>Usar sessão</button></div> })}{!data.packageSales.length && <EmptyState>Nenhum pacote vendido.</EmptyState>}</section>}
    {draft && <Modal title={draft.id ? 'Editar pacote' : 'Novo pacote'} close={() => setDraft(null)}><form onSubmit={async event => { event.preventDefault(); const items = Object.entries(quantities).filter(([, quantity]) => quantity > 0).map(([service_id, quantity]) => ({ service_id, quantity })); if (await run('save_package', { id: draft.id || null, name: draft.name, description: draft.description, price: draft.price_cents, active: draft.active, items })) setDraft(null) }}><label className="field"><span>Nome</span><input required minLength={2} value={draft.name} onChange={event => setDraft({ ...draft, name: event.target.value })} /></label><label className="field"><span>Descrição</span><input value={draft.description ?? ''} onChange={event => setDraft({ ...draft, description: event.target.value })} /></label><label className="field"><span>Valor do pacote (R$)</span><input required min="0.01" step="0.01" type="number" value={draft.price_cents / 100} onChange={event => setDraft({ ...draft, price_cents: Math.round(Number(event.target.value) * 100) })} /></label><fieldset className="package-services"><legend>Serviços incluídos</legend>{services.filter(service => service.ativo).map(service => <label key={service.id}><span>{service.nome}</span><input aria-label={`Quantidade de ${service.nome}`} type="number" min="0" step="1" value={quantities[service.id] ?? 0} onChange={event => setQuantities({ ...quantities, [service.id]: Number(event.target.value) })} /></label>)}</fieldset><label className="check"><input type="checkbox" checked={draft.active} onChange={event => setDraft({ ...draft, active: event.target.checked })} />Disponível para venda</label>{error && <p className="form-error">{error}</p>}<button className="primary" disabled={busy}>Salvar pacote</button></form></Modal>}
    {saleOpen && <Modal title="Venda de pacote" close={() => setSaleOpen(false)}><form onSubmit={async event => { event.preventDefault(); if (await run('sell_package', { package_id: salePackage, customer_id: saleCustomer, method: saleMethod })) { setSaleOpen(false); setView('sales') } }}><label className="field"><span>Cliente</span><select required value={saleCustomer} onChange={event => setSaleCustomer(event.target.value)}><option value="">Escolha o cliente</option>{data.customers.map(customer => <option key={customer.id} value={customer.id}>{customer.name} · {customer.phone}</option>)}</select></label><label className="field"><span>Pacote</span><select required value={salePackage} onChange={event => setSalePackage(event.target.value)}><option value="">Escolha o pacote</option>{data.packages.filter(item => item.active).map(item => <option key={item.id} value={item.id}>{item.name} · {money(item.price_cents)}</option>)}</select></label><label className="field"><span>Pagamento</span><select value={saleMethod} onChange={event => setSaleMethod(event.target.value)}>{Object.entries(methods).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label>{!activeCash && <p className="form-error">Abra o Caixa antes de vender um pacote.</p>}{error && <p className="form-error">{error}</p>}<button className="primary" disabled={busy || !activeCash}>Registrar venda</button></form></Modal>}
    {redeem && <Modal title="Usar sessão" close={() => setRedeem(null)}><form onSubmit={async event => { event.preventDefault(); if (await run('redeem_package', { sale_id: redeem.id, service_id: redeemService })) setRedeem(null) }}><p><strong>{redeem.customer_name}</strong> · {redeem.package_name}</p><label className="field"><span>Serviço</span><select required value={redeemService} onChange={event => setRedeemService(event.target.value)}><option value="">Escolha o serviço utilizado</option>{redeem.balances.filter(item => item.remaining > 0).map(item => <option key={item.service_id} value={item.service_id}>{item.service_name} · {item.remaining} restantes</option>)}</select></label>{error && <p className="form-error">{error}</p>}<button className="primary" disabled={busy}>Confirmar uso</button></form></Modal>}
  </Page>
}

export function CompanySettings() {
  const { data, run, busy, error } = useOperations()
  const blank: BusinessSettings = { id: true, name: 'Machado Barbearia', legal_name: '', email: '', phone: '', postal_code: '', street: '', city: '', state: '', instagram: '', website: '' }
  const [draft, setDraft] = useState<BusinessSettings>(data.business[0] ?? blank)
  const field = (key: keyof BusinessSettings, label: string, type = 'text') => <label className="field"><span>{label}</span><input type={type} value={String(draft[key] ?? '')} onChange={event => setDraft({ ...draft, [key]: event.target.value })} /></label>
  return <Page title="Empresa"><section className="panel operation-panel company-form"><form onSubmit={async event => { event.preventDefault(); await run('save_business', { ...draft }) }}><div className="form-grid">{field('name','Nome da empresa')}{field('legal_name','Razão social')}{field('email','E-mail','email')}{field('phone','Telefone','tel')}{field('postal_code','CEP')}{field('street','Endereço')}{field('city','Cidade')}{field('state','Estado')}{field('instagram','Instagram')}{field('website','Site')}</div>{error && <p className="form-error">{error}</p>}<button className="primary" disabled={busy}>{busy ? 'Salvando…' : 'Salvar empresa'}</button></form></section></Page>
}
