import { useEffect, useState, type ReactNode } from 'react'
import { Link } from 'react-router-dom'
import { useOperations } from './OperationsStore'
import { useCatalog } from './CatalogStore'
import { supabase } from './supabaseClient'
import { cashBalance, commandTotal, dateTime, dayKey, exportCsv, labels, methods, money, summarize, type Appointment, type Customer, type Product } from './operations'
import { uploadCatalogPhoto } from './media'

export function Page({ title, text, action, children }: { title: string; text?: string; action?: ReactNode; children: ReactNode }) {
  return <section className="page"><div className="page-head"><div><h2>{title}</h2>{text && <p>{text}</p>}</div>{action}</div>{children}</section>
}
export function Modal({ title, close, children }: { title: string; close: () => void; children: ReactNode }) {
  return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label={title}><div className="modal-head"><h2>{title}</h2><button className="outline small" onClick={close}>Fechar</button></div>{children}</section></div>
}
function Metrics({ entries }: { entries: [string, string | number][] }) { return <div className="stats-grid">{entries.map(([label, value]) => <article className="stat-card" key={label}><span>{label}</span><strong>{value}</strong></article>)}</div> }
function Method({ value, set }: { value: string; set: (v: string) => void }) { return <fieldset className="payment-methods"><legend>Recebimento</legend><div>{Object.entries(methods).map(([key, label]) => <button type="button" key={key} className={value === key ? 'selected' : ''} onClick={() => set(key)}>{label}</button>)}</div></fieldset> }
function Empty({ children = 'Nenhum registro neste período.' }: { children?: ReactNode }) { return <p className="empty">{children}</p> }
function CashActivity({ movements }: { movements: { created_at: string; amount_cents: number }[] }) {
  const days = Array.from({ length: 7 }, (_, index) => {
    const date = new Date()
    date.setDate(date.getDate() - (6 - index))
    const key = date.toISOString().slice(0, 10)
    const amount = movements.filter(m => dayKey(m.created_at) === key).reduce((sum, m) => sum + m.amount_cents, 0)
    return { key, amount, label: date.toLocaleDateString('pt-BR', { weekday: 'narrow' }) }
  })
  const largest = Math.max(...days.map(day => Math.abs(day.amount)), 1)
  const total = days.reduce((sum, day) => sum + day.amount, 0)
  return <section className="panel operation-panel cash-activity-card"><div className="panel-title"><div><h3>Movimento da semana</h3><p>Entradas e saídas dos últimos 7 dias.</p></div><strong className={total < 0 ? 'red' : 'green'}>{total < 0 ? '−' : '+'}{money(Math.abs(total))}</strong></div><div className="cash-chart" aria-label={`Movimento acumulado de ${money(total)} na semana`}>{days.map((day, index) => <div className={day.amount < 0 ? 'negative' : index === days.length - 1 ? 'current' : ''} key={day.key}><i style={{ height: `${Math.max(9, Math.round(Math.abs(day.amount) / largest * 100))}%` }} /><span>{day.label}</span></div>)}</div></section>
}
export function AppointmentIdentity({ appointment: a }: { appointment: Appointment }) {
  return <div className="appointment-identity"><strong>{a.customer_name} <span className="professional-label">· {a.professional_name}</span></strong><span>{a.service_name} · {money(a.expected_price_cents)}</span><small>{dateTime(a.starts_at)} · {labels[a.status] ?? a.status}</small></div>
}

export function Dashboard() {
  const { data } = useOperations(); const today = dayKey(); const summary = summarize(data, today, today)
  const pending = data.commissions.filter(c => c.status === 'pending').reduce((s, c) => s + c.commission_cents, 0)
  return <Page title="Visão geral">
    <Metrics entries={[["Agendamentos hoje", summary.appointments.length], ['Recebido hoje', money(summary.received)], ['Atendimentos concluídos hoje', summary.completed.length], ['Repasses pendentes', money(pending)]]} />
    <div className="management-grid"><section className="panel operation-panel"><div className="panel-title"><h3>Agenda de hoje</h3><Link to="/admin/agenda">Abrir agenda</Link></div>{summary.appointments.map(a => <div className="record-row" key={a.id}><AppointmentIdentity appointment={a} /></div>)}{!summary.appointments.length && <Empty />}</section>
    <section className="panel operation-panel"><h3>Estoque baixo</h3>{data.products.filter(p => p.active && p.quantity <= p.minimum_quantity).map(p => <p key={p.id}>{p.name} · {p.quantity} un.</p>)}{!data.products.some(p => p.active && p.quantity <= p.minimum_quantity) && <Empty>Sem produtos abaixo do mínimo.</Empty>}</section></div>
  </Page>
}

export function AppointmentModal({ close }: { close: () => void }) {
  const { services, professionals } = useCatalog(); const { run, busy, error } = useOperations()
  const [name, setName] = useState(''); const [phone, setPhone] = useState(''); const [service, setService] = useState(services.find(s => s.ativo)?.id ?? ''); const [professional, setProfessional] = useState(professionals.find(p => p.ativo)?.id ?? '')
  const [date, setDate] = useState(dayKey()); const [time, setTime] = useState(''); const [price, setPrice] = useState(String(services.find(s => s.id === service)?.preco ?? 0)); const [slots,setSlots]=useState<Array<{time:string;available:boolean}>>([]); const [loadingSlots,setLoadingSlots]=useState(false)
  useEffect(()=>{ let alive=true; setTime(''); if(!supabase||!service||!professional){setSlots([]);return} setLoadingSlots(true); void supabase.rpc('public_booking_slots',{chosen_service:service,booking_day:date,preferred_professional:professional}).then(({data,error:slotError})=>{if(!alive)return;const found=(data??[]) as Array<{slot_time:string;available:boolean}>;setSlots(slotError ? [] : found.map(slot => ({time:String(slot.slot_time).slice(0,5),available:Boolean(slot.available)})));setLoadingSlots(false)});return()=>{alive=false}},[service,professional,date])
  return <Modal title="Novo agendamento" close={close}><form onSubmit={async e => { e.preventDefault(); if (await run('create_appointment', { name, phone, professional_id: professional, service_id: service, starts_at: `${date}T${time}:00-03:00`, amount: Math.round(Number(price) * 100) })) close() }}><div className="form-grid">
    <label className="field"><span>Cliente</span><input required minLength={2} value={name} onChange={e => setName(e.target.value)} /></label><label className="field"><span>WhatsApp</span><input required type="tel" minLength={10} value={phone} onChange={e => setPhone(e.target.value)} /></label>
    <label className="field"><span>Profissional</span><select required value={professional} onChange={e => setProfessional(e.target.value)}><option value="">Selecione</option>{professionals.filter(p => p.ativo).map(p => <option value={p.id} key={p.id}>{p.nome}</option>)}</select></label>
    <label className="field"><span>Serviço</span><select required value={service} onChange={e => { setService(e.target.value); setPrice(String(services.find(s => s.id === e.target.value)?.preco ?? 0)) }}><option value="">Selecione</option>{services.filter(s => s.ativo).map(s => <option value={s.id} key={s.id}>{s.nome}</option>)}</select></label>
    <label className="field"><span>Data</span><input type="date" required min={dayKey()} value={date} onChange={e => setDate(e.target.value)} /></label><label className="field"><span>Valor (R$)</span><input required type="number" min="0" step="0.01" value={price} onChange={e => setPrice(e.target.value)} /></label></div>
    <div className="admin-slot-picker"><span>Horário</span>{loadingSlots?<p>Buscando horários…</p>:<div>{slots.map(slot=><button type="button" key={slot.time} disabled={!slot.available} className={`${time===slot.time?'selected':''} ${!slot.available?'unavailable':''}`} onClick={()=>setTime(slot.time)}>{slot.time}{!slot.available&&<small>Ocupado</small>}</button>)}</div>}</div>
    {!loadingSlots&&professional&&service&&!slots.some(slot=>slot.available)&&<p className="form-hint">Não há horário livre para esse profissional e serviço nesta data.</p>}{error && <p role="alert" className="form-error">{error}</p>}<button disabled={busy || !time} className="primary">{busy ? 'Salvando…' : 'Salvar agendamento'}</button></form></Modal>
}

export function Agenda({ onNew }: { onNew: () => void }) {
  const { data, run, busy, error } = useOperations(); const { professionals } = useCatalog()
  const [date, setDate] = useState(dayKey()); const [professional, setProfessional] = useState(''); const [search, setSearch] = useState(''); const [all, setAll] = useState(false)
  const [filtersOpen, setFiltersOpen] = useState(false)
  const [confirmation, setConfirmation] = useState<{ appointment: Appointment; status: string } | null>(null)
  const [removing, setRemoving] = useState<Appointment | null>(null)
  const [actualPrice, setActualPrice] = useState('')
  const rows = data.appointments.filter(a => a.status !== 'cancelled' && (all || dayKey(a.starts_at) === date) && (!professional || a.professional_id === professional) && `${a.customer_name} ${a.professional_name} ${a.service_name}`.toLocaleLowerCase().includes(search.toLocaleLowerCase())).sort((a,b) => a.starts_at.localeCompare(b.starts_at))
  const shiftDate = (amount: number) => { const next = new Date(`${date}T12:00:00-03:00`); next.setDate(next.getDate() + amount); setDate(dayKey(next)); setAll(false) }
  const dateLabel = new Date(`${date}T12:00:00-03:00`).toLocaleDateString('pt-BR', { weekday: 'long', day: '2-digit', month: 'long' })
  return <Page title="Agenda" action={<div className="row-actions"><button className="outline" onClick={() => setFiltersOpen(value => !value)}>{filtersOpen ? 'Fechar filtros' : 'Filtros'}</button><button className="primary" onClick={onNew}>Novo</button></div>}>
    <section className="agenda-daybar" aria-label="Navegação por data"><button aria-label="Dia anterior" onClick={() => shiftDate(-1)}>‹</button><div><span>{all ? 'Todos os agendamentos' : 'Agenda do dia'}</span><strong>{all ? `${rows.length} registros` : dateLabel}</strong></div><button aria-label="Próximo dia" onClick={() => shiftDate(1)}>›</button></section>
    {filtersOpen && <div className="management-filters filter-panel"><label>Data<input type="date" value={date} onChange={e => { setDate(e.target.value); setAll(false) }} /></label><label>Profissional<select value={professional} onChange={e => setProfessional(e.target.value)}><option value="">Todos</option>{professionals.map(p => <option key={p.id} value={p.id}>{p.nome}</option>)}</select></label><label>Buscar<input placeholder="Cliente, profissional ou serviço" value={search} onChange={e => setSearch(e.target.value)} /></label><label className="check"><input type="checkbox" checked={all} onChange={e => setAll(e.target.checked)} /> Todas as datas</label></div>}
    <section className="agenda-timeline">{rows.map(a => <article className={`agenda-timeline-card ${a.status}`} key={a.id}><time>{new Date(a.starts_at).toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })}</time><div className="agenda-timeline-dot" /><div className="agenda-timeline-main"><span className="badge">{labels[a.status] ?? a.status}</span><AppointmentIdentity appointment={a} /></div><div className="row-actions">{!['completed','cancelled','no_show'].includes(a.status) && <>
      <button className="primary small" disabled={busy} onClick={() => { setActualPrice(String(a.expected_price_cents / 100)); setConfirmation({ appointment: a, status: 'completed' }) }}>Pronto</button><button className="outline small" disabled={busy} onClick={() => setConfirmation({ appointment: a, status: 'no_show' })}>Faltou</button>
    </>}</div></article>)}{!rows.length && <section className="panel operation-panel"><Empty>Nenhum horário para este dia.</Empty></section>}</section>
    {confirmation && <Modal title={confirmation.status === 'completed' ? 'Enviar para receber?' : 'Marcar falta?'} close={() => setConfirmation(null)}><AppointmentIdentity appointment={confirmation.appointment} /><p>{confirmation.status === 'completed' ? 'A comanda ficará pronta no Caixa.' : 'Este horário será liberado.'}</p>{confirmation.status === 'completed' && confirmation.appointment.expected_price_cents <= 0 && <label className="field"><span>Valor (R$)</span><input autoFocus required type="number" min="0.01" step="0.01" value={actualPrice} onChange={e => setActualPrice(e.target.value)} /></label>}{error && <p className="form-error">{error}</p>}<button className="primary" disabled={busy} onClick={async () => { if (confirmation.status === 'completed' && confirmation.appointment.expected_price_cents <= 0 && !(await run('set_price', { id: confirmation.appointment.id, amount: Math.round(Number(actualPrice) * 100) }))) return; if (await run('set_status', { id: confirmation.appointment.id, status: confirmation.status })) setConfirmation(null) }}>{confirmation.status === 'completed' ? 'Enviar para Caixa' : 'Confirmar falta'}</button></Modal>}
    {removing && <Modal title="Remover agendamento" close={() => setRemoving(null)}><AppointmentIdentity appointment={removing}/><p>Esse horário será removido da agenda. O histórico financeiro permanece protegido.</p>{error && <p className="form-error">{error}</p>}<button className="danger" disabled={busy} onClick={async()=>{if(await run('set_status',{id:removing.id,status:'cancelled'}))setRemoving(null)}}>Remover da agenda</button></Modal>}
  </Page>
}

export function Customers() {
  const { data, run, busy, error } = useOperations(); const [search, setSearch] = useState(''); const [draft, setDraft] = useState<Customer | null>(null); const [history, setHistory] = useState<string | null>(null)
  const visible = data.customers.filter(c => `${c.name} ${c.phone}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()))
  const remove = async () => { if (!draft?.id || !window.confirm('Remover este cliente? Primeiro remova os agendamentos dele, se houver.')) return; if (await run('delete_customer',{ id:draft.id })) setDraft(null) }
  return <Page title="Clientes" action={<button className="primary" onClick={() => setDraft({ id: '', name: '', phone: '', notes: '' })}>Novo</button>}>
    <div className="management-filters"><label>Buscar cliente<input value={search} onChange={e => setSearch(e.target.value)} placeholder="Nome ou telefone" /></label></div><section className="customer-list">{visible.map(c => {
      const visits = data.appointments.filter(a => a.customer_id === c.id && a.status === 'completed'); const commands = new Set(data.commands.filter(cmd => cmd.customer_id === c.id).map(cmd => cmd.id)); const paid = data.payments.filter(p => commands.has(p.command_id) && !p.reversed_at).reduce((s, p) => s + p.amount_cents, 0)
      const initials = c.name.split(' ').filter(Boolean).slice(0,2).map(part => part[0]).join('').toUpperCase()
      return <article className="customer-card" key={c.id}><span className="customer-avatar">{initials || 'C'}</span><div className="customer-card-main"><strong>{c.name}</strong><small>{c.phone}</small><div><span>{visits.length} {visits.length === 1 ? 'visita' : 'visitas'}</span><b>{money(paid)}</b></div></div><div className="row-actions"><button className="outline small" onClick={() => setHistory(c.id)}>Histórico</button><button className="icon-btn" aria-label={`Editar ${c.name}`} onClick={() => setDraft({ ...c })}>•••</button></div></article>
    })}{!visible.length && <section className="panel operation-panel"><Empty>Nenhum cliente encontrado.</Empty></section>}</section>
    {draft && <Modal title={draft.id ? 'Editar cliente' : 'Novo cliente'} close={() => setDraft(null)}><form onSubmit={async e => { e.preventDefault(); if (await run('save_customer', { ...draft, id: draft.id || null })) setDraft(null) }}><label className="field"><span>Nome</span><input required minLength={2} value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} /></label><label className="field"><span>Telefone</span><input required type="tel" minLength={10} value={draft.phone} onChange={e => setDraft({ ...draft, phone: e.target.value })} /></label><label className="field"><span>Observações</span><textarea value={draft.notes ?? ''} onChange={e => setDraft({ ...draft, notes: e.target.value })} /></label>{error && <p className="form-error">{error}</p>}<div className="row-actions"><button className="primary" disabled={busy}>Salvar cliente</button>{draft.id && <button className="danger-button" type="button" disabled={busy} onClick={()=>void remove()}>Excluir cliente</button>}</div></form></Modal>}
    {history && <Modal title="Histórico do cliente" close={() => setHistory(null)}>{data.appointments.filter(a => a.customer_id === history).map(a => <div className="record-row" key={a.id}><AppointmentIdentity appointment={a} /></div>)}{!data.appointments.some(a => a.customer_id === history) && <Empty />}</Modal>}
  </Page>
}

export function Orders({ onNew }: { onNew: () => void }) {
  const { data, run, busy, error } = useOperations(); const [filter, setFilter] = useState(''); const [receive, setReceive] = useState(''); const [method, setMethod] = useState('pix'); const [priceId, setPriceId] = useState(''); const [price, setPrice] = useState(''); const [details, setDetails] = useState(''); const [productId, setProductId] = useState(''); const [quantity, setQuantity] = useState('1')
  const selected = data.commands.find(c => c.id === receive)
  const command = data.commands.find(c => c.id === details)
  const visible = data.commands.filter(c => !filter || c.status === filter)
  const products = data.products.filter(p => p.active && p.quantity > 0)
  const statusCount = (status: string) => data.commands.filter(c => c.status === status).length
  return <Page title="Comandas" action={<button className="primary" onClick={onNew}>Nova</button>}>
    <div className="command-filters" aria-label="Filtrar comandas"><button className={!filter ? 'active' : ''} onClick={() => setFilter('')}>Todas <span>{data.commands.length}</span></button>{['open','awaiting_payment','closed'].map(status => <button className={filter === status ? 'active' : ''} onClick={() => setFilter(status)} key={status}>{status === 'awaiting_payment' ? 'Prontas' : labels[status]} <span>{statusCount(status)}</span></button>)}</div>
    <section className="command-list">{visible.map(c => { const a = data.appointments.find(a => a.id === c.appointment_id); const itemCount = data.items.filter(item => item.command_id === c.id).reduce((sum,item) => sum + item.quantity, 0); return <article className={`command-card ${c.status}`} key={c.id}><button className="command-card-main" onClick={() => { setDetails(c.id); setProductId(''); setQuantity('1') }}><div className="command-card-top"><span className={`status ${c.status === 'closed' ? 'positive' : c.status === 'awaiting_payment' ? 'warning' : 'muted'}`}>{c.status === 'awaiting_payment' ? 'Pronta' : labels[c.status]}</span><small>{itemCount} {itemCount === 1 ? 'item' : 'itens'}</small></div><strong>{a?.customer_name ?? data.customers.find(x => x.id === c.customer_id)?.name ?? 'Cliente'}</strong><p>{a ? `${a.service_name} · ${a.professional_name}` : 'Comanda manual'}</p></button><div className="command-card-footer"><strong>{money(commandTotal(data, c))}</strong><div>{c.status === 'open' && a && <Link className="outline small" to="/admin/agenda">Atender</Link>}{c.status === 'awaiting_payment' && <button className="primary small" onClick={() => setReceive(c.id)}>Receber</button>}<button className="text-button" onClick={() => { setDetails(c.id); setProductId(''); setQuantity('1') }}>Itens</button></div></div></article> })}{!visible.length && <section className="panel operation-panel"><Empty>Nenhuma comanda neste status.</Empty></section>}</section>
    {selected && <Modal title="Registrar recebimento" close={() => setReceive('')}><p>Total: <strong>{money(commandTotal(data, selected))}</strong></p><Method value={method} set={setMethod} /><p>Confirme somente depois de receber do cliente. O registro entrará no caixa aberto.</p>{error && <p className="form-error">{error}</p>}<button className="primary" disabled={busy} onClick={async () => { if (await run('receive', { id: receive, method })) setReceive('') }}>Confirmar pagamento recebido</button></Modal>}
    {priceId && <Modal title="Valor do atendimento" close={() => setPriceId('')}><form onSubmit={async e => { e.preventDefault(); if (await run('set_price', { id: priceId, amount: Math.round(Number(price)*100) })) setPriceId('') }}><label className="field"><span>Valor (R$)</span><input required type="number" min="0.01" step="0.01" value={price} onChange={e => setPrice(e.target.value)} /></label>{error && <p className="form-error">{error}</p>}<button className="primary" disabled={busy}>Salvar valor</button></form></Modal>}
    {command && <Modal title="Detalhes da comanda" close={() => setDetails('')}><div className="command-detail-head"><span className="badge">{labels[command.status]}</span><strong>{money(commandTotal(data, command))}</strong></div><section className="command-items">{data.items.filter(item => item.command_id === command.id).map(item => <div key={item.id}><span>{item.description} <small>× {item.quantity}</small></span><strong>{money(item.unit_price_cents * item.quantity)}</strong></div>)}</section>{command.status === 'awaiting_payment' && <form className="command-product-form" onSubmit={async event => { event.preventDefault(); if (await run('add_command_product', { command_id: command.id, product_id: productId, quantity: Number(quantity) })) { setProductId(''); setQuantity('1') } }}><h3>Adicionar produto</h3>{products.length ? <><label className="field"><span>Produto</span><select required value={productId} onChange={e => setProductId(e.target.value)}><option value="">Escolha um produto</option>{products.map(product => <option value={product.id} key={product.id}>{product.name} · {money(product.sale_price_cents)} · {product.quantity} un.</option>)}</select></label><label className="field"><span>Quantidade</span><input required min="1" type="number" step="1" value={quantity} onChange={e => setQuantity(e.target.value)} /></label><button className="outline" disabled={busy || !productId}>Adicionar à comanda</button></> : <p className="form-hint">Não há produto ativo com estoque disponível.</p>}</form>}{command.status === 'open' && <p className="form-hint">Conclua o atendimento pela Agenda antes de adicionar produtos ou receber.</p>}{error && <p className="form-error">{error}</p>}</Modal>}
  </Page>
}

export function CashManagement() {
  const { data, run, busy, error } = useOperations(); const { professionals } = useCatalog()
  const [dialog, setDialog] = useState(''); const [amount, setAmount] = useState(''); const [notes, setNotes] = useState(''); const [method, setMethod] = useState('cash'); const [type, setType] = useState('expense'); const [professionalId, setProfessionalId] = useState(''); const [entryIds, setEntryIds] = useState<string[]>([]); const [receive, setReceive] = useState(''); const [filtersOpen,setFiltersOpen]=useState(false); const [commissionView,setCommissionView]=useState('pending'); const [commissionProfessional,setCommissionProfessional]=useState('')
  const active = data.sessions.find(s => !s.closed_at); const [chosenSession, setChosenSession] = useState(''); const shown = data.sessions.find(s => s.id === chosenSession) ?? active ?? data.sessions[0]
  const pending = data.commissions.filter(e => e.status === 'pending' && e.commission_cents > 0)
  const movements = data.movements.filter(m => m.session_id === shown?.id)
  const pendingPayments = data.commands.filter(c => c.status === 'awaiting_payment')
  const payment = data.commands.find(c => c.id === receive)
  const openDialog = (value: string) => { setDialog(value); setAmount(''); setNotes(''); setMethod('cash') }
  const submit = async (e: React.FormEvent) => {
    e.preventDefault()
    const action = dialog === 'open' ? 'open_cash' : dialog === 'close' ? 'close_cash' : dialog === 'pay' ? 'pay_commissions' : 'move_cash'
    if (await run(action, { id: dialog === 'pay' ? professionalId : active?.id, amount: Math.round(Number(amount)*100), method, type, notes, entries: entryIds })) setDialog('')
  }
  const visibleCommissions=data.commissions.filter(e=>e.commission_cents>0&&e.status===commissionView&&(!commissionProfessional||e.professional_id===commissionProfessional))
  return <Page title="Caixa" action={<div className="row-actions"><button className="outline" onClick={()=>setFiltersOpen(v=>!v)}>{filtersOpen?'Fechar filtros':'Filtros'}</button><button className="primary" disabled={busy} onClick={() => openDialog(active ? 'close' : 'open')}>{active ? 'Fechar caixa' : 'Abrir caixa'}</button></div>}>
    {filtersOpen&&<div className="management-filters filter-panel"><label>Caixa<select value={shown?.id ?? ''} onChange={e => setChosenSession(e.target.value)}>{!data.sessions.length && <option value="">Nenhum caixa aberto</option>}{data.sessions.map(s => <option key={s.id} value={s.id}>{dateTime(s.opened_at)} · {s.closed_at ? 'Fechado' : 'Aberto'}</option>)}</select></label><label>Repasses<select value={commissionView} onChange={e=>setCommissionView(e.target.value)}><option value="pending">Pendentes</option><option value="paid">Pagos</option></select></label><label>Profissional<select value={commissionProfessional} onChange={e=>setCommissionProfessional(e.target.value)}><option value="">Todos</option>{professionals.map(p=><option value={p.id} key={p.id}>{p.nome}</option>)}</select></label></div>}
    <Metrics entries={[["Caixa", active ? 'Aberto' : 'Fechado'], ['Saldo', money(shown ? cashBalance(data, shown) : 0)], ['Prontas', pendingPayments.length], ['Repasses', money(pending.reduce((s,e) => s+e.commission_cents,0))]]} />
    <CashActivity movements={movements} />
    <section className="panel operation-panel ready-receipts"><div className="panel-title"><h3>Prontas para receber</h3><span>{pendingPayments.length}</span></div>{pendingPayments.map(command => { const appointment = data.appointments.find(a => a.id === command.appointment_id); return <div className="record-row" key={command.id}><div>{appointment && <AppointmentIdentity appointment={appointment} />}</div><strong>{money(commandTotal(data, command))}</strong><button className="primary small" disabled={!active || busy} onClick={() => { setMethod('pix'); setReceive(command.id) }}>Receber</button></div> })}{!pendingPayments.length && <Empty>Sem recebimentos pendentes.</Empty>}</section>
    <section className="panel operation-panel"><div className="panel-title"><h3>Movimentações</h3><button className="outline small" disabled={!active || busy} onClick={() => openDialog('move')}>Novo lançamento</button></div>
    {shown?.closed_at && <p>Contado: {money(shown.declared_balance_cents ?? 0)} · Diferença: {money((shown.declared_balance_cents ?? 0)-cashBalance(data, shown))}</p>}
    {movements.map(m => { const cmd = data.commands.find(c => c.id === m.command_id); const a = data.appointments.find(a => a.id === cmd?.appointment_id); return <div className="record-row" key={m.id}><div><strong>{m.notes}</strong><p>{a ? `${a.customer_name} · ${a.professional_name} · ${a.service_name}` : ''}</p><small>{dateTime(m.created_at)} · {methods[m.payment_method]}</small></div><strong className={m.amount_cents < 0 ? 'red' : 'green'}>{money(m.amount_cents)}</strong></div> })}{!movements.length && <Empty />}</section>
    <section className="panel operation-panel"><h3>{commissionView==='pending'?'Repasses pendentes':'Repasses pagos'}</h3>{commissionView==='pending'?[...new Set(visibleCommissions.map(e=>e.professional_id))].map(id => { const entries = visibleCommissions.filter(e => e.professional_id === id); return <div className="record-row" key={id}><strong>{professionals.find(p => p.id === id)?.nome ?? data.appointments.find(a => a.professional_id === id)?.professional_name ?? 'Profissional'}</strong><span>{entries.length} serviços · {money(entries.reduce((s,e) => s+e.commission_cents,0))}</span><button className="primary small" disabled={!active || busy} onClick={() => { setProfessionalId(id); setEntryIds(entries.map(e => e.id)); openDialog('pay') }}>Pagar repasse</button></div> }):visibleCommissions.map(e=><div className="record-row" key={e.id}><span>{professionals.find(p=>p.id===e.professional_id)?.nome??'Profissional'} · {e.paid_at?dateTime(e.paid_at):''}</span><strong>{money(e.commission_cents)}</strong></div>)}{!visibleCommissions.length&&<Empty>{commissionView==='pending'?'Nenhum repasse pendente.':'Nenhum repasse pago neste filtro.'}</Empty>}</section>
    {dialog && <Modal title={{ open: 'Abrir caixa', close: 'Fechar caixa', move: 'Novo lançamento', pay: 'Registrar repasse' }[dialog] ?? ''} close={() => setDialog('')}><form onSubmit={submit}>
      {dialog === 'pay' ? <p>Confirmar o pagamento de {money(pending.filter(e => entryIds.includes(e.id)).reduce((s,e) => s+e.commission_cents,0))} ao profissional?</p> : <label className="field"><span>{dialog === 'open' ? 'Dinheiro inicial (R$)' : dialog === 'close' ? 'Dinheiro contado no fechamento (R$)' : 'Valor (R$)'}</span><input autoFocus required type="number" min={dialog === 'move' ? '0.01' : '0'} step="0.01" value={amount} onChange={e => setAmount(e.target.value)} /></label>}
      {dialog === 'move' && <label className="field"><span>Tipo</span><select value={type} onChange={e => setType(e.target.value)}><option value="expense">Despesa</option><option value="withdrawal">Retirada</option><option value="reinforcement">Reforço</option></select></label>}
      {['pay','move'].includes(dialog) && <Method value={method} set={setMethod} />}{['close','move'].includes(dialog) && <label className="field"><span>Descrição / observação</span><input required={dialog === 'move'} minLength={dialog === 'move' ? 3 : undefined} value={notes} onChange={e => setNotes(e.target.value)} /></label>}
      {dialog === 'close' && active && <p>Dinheiro esperado: {money(cashBalance(data, active))}. Pix e cartões ficam separados do dinheiro físico.</p>}{error && <p className="form-error">{error}</p>}<button className="primary" disabled={busy}>Confirmar</button></form></Modal>}
    {payment && <Modal title="Confirmar pagamento" close={() => setReceive('')}><p>Total: <strong>{money(commandTotal(data, payment))}</strong></p><Method value={method} set={setMethod} />{error && <p className="form-error">{error}</p>}<button className="primary" disabled={busy || !active} onClick={async () => { if (await run('receive', { id: payment.id, method })) setReceive('') }}>Pagamento recebido</button></Modal>}
  </Page>
}

export function Reports() {
  const { data } = useOperations(); const { professionals } = useCatalog(); const [from, setFrom] = useState(dayKey().slice(0,7)+'-01'); const [to, setTo] = useState(dayKey()); const [professional, setProfessional] = useState(''); const [filtersOpen,setFiltersOpen]=useState(false)
  const summary = summarize(data, from, to, professional)
  const expenses = data.movements.filter(m => m.type==='expense' && dayKey(m.created_at)>=from && dayKey(m.created_at)<=to).reduce((s,m) => s-m.amount_cents,0)
  const ids = [...new Set(summary.completed.map(a => a.professional_id))]
  const exportRows = () => exportCsv(`relatorio-${from}-${to}.csv`, [['Cliente','Profissional','Serviço','Data','Status','Valor (R$)'], ...summary.appointments.map(a => [a.customer_name,a.professional_name,a.service_name,dateTime(a.starts_at),labels[a.status],(a.expected_price_cents/100).toFixed(2)])])
  return <Page title="Relatórios" text="Resumo simples da operação." action={<div className="row-actions"><button className="outline" onClick={()=>setFiltersOpen(v=>!v)}>{filtersOpen?'Fechar filtros':'Filtros'}</button><button className="outline" onClick={exportRows}>Exportar CSV</button></div>}>
    {filtersOpen&&<div className="management-filters filter-panel"><label>De<input type="date" value={from} onChange={e => setFrom(e.target.value)} /></label><label>Até<input type="date" min={from} value={to} onChange={e => setTo(e.target.value)} /></label><label>Profissional<select value={professional} onChange={e => setProfessional(e.target.value)}><option value="">Todos</option>{professionals.map(p => <option key={p.id} value={p.id}>{p.nome}</option>)}</select></label></div>}
    <Metrics entries={[["Faturamento", money(summary.gross)], ['Recebido', money(summary.received)], ['A repassar', money(summary.pending)], ['Resultado', money(summary.shop-expenses)]]} />
    <section className="panel operation-panel"><h3>Por profissional</h3>{ids.map(id => { const s = summarize(data, from, to, id); return <div className="record-row" key={id}><strong>{summary.completed.find(a => a.professional_id === id)?.professional_name}</strong><span>{s.completed.length} atendimentos · {money(s.gross)}</span><span>Comissão: {money(s.earned)}</span></div> })}{!ids.length && <Empty />}</section>
    <section className="panel operation-panel"><h3>Atendimentos no período</h3>{summary.appointments.map(a => <div className="record-row" key={a.id}><AppointmentIdentity appointment={a} /></div>)}{!summary.appointments.length && <Empty />}</section>
  </Page>
}

export function Products() {
  const { data, run, busy, error } = useOperations(); const [draft, setDraft] = useState<Product | null>(null); const [stock, setStock] = useState<Product | null>(null); const [photo,setPhoto]=useState<File|null>(null); const [delta,setDelta] = useState(''); const [notes,setNotes] = useState('')
  const fresh: Product = { id:'',name:'',category:'',quantity:0,minimum_quantity:0,sale_price_cents:0,cost_cents:0,active:true,photo_url:null }
  return <Page title="Produtos e estoque" text="Cadastros e movimentações salvos no sistema." action={<button className="primary" onClick={() => {setDraft(fresh);setPhoto(null)}}>Novo produto</button>}><section className="product-grid">{data.products.map(p => <article className="product-card" key={p.id}>{p.photo_url?<img className="product-photo" src={p.photo_url} alt=""/>:<div className="product-photo product-placeholder">Produto</div>}<div className="product-card-body"><strong>{p.name}</strong><p>{p.category || 'Sem categoria'} · {money(p.sale_price_cents)}</p><span className={p.quantity<=p.minimum_quantity ? 'low' : ''}>{p.quantity} un. · mín. {p.minimum_quantity}</span><div className="row-actions"><button className="outline small" onClick={() => {setDraft({ ...p });setPhoto(null)}}>Editar</button><button className="outline small" onClick={() => { setStock(p); setDelta(''); setNotes('') }}>Estoque</button></div></div></article>)}{!data.products.length && <section className="panel operation-panel"><Empty /></section>}</section>
    {draft && <Modal title="Produto" close={() => setDraft(null)}><form onSubmit={async e => { e.preventDefault(); try {let photoUrl=draft.photo_url??null;if(photo)photoUrl=await uploadCatalogPhoto(photo,'products');if (await run('save_product_profile', { id:draft.id||null,name:draft.name,category:draft.category,price:draft.sale_price_cents,cost:draft.cost_cents,minimum:draft.minimum_quantity,active:draft.active,photo_url:photoUrl })) setDraft(null)} catch(err) { alert(err instanceof Error?err.message:'Não foi possível enviar a foto.') } }}><label className="field"><span>Foto (4:5)</span><input accept="image/*" type="file" onChange={e=>setPhoto(e.target.files?.[0]??null)}/></label>{draft.photo_url&&!photo&&<img className="photo-preview" src={draft.photo_url} alt=""/>}<label className="field"><span>Nome</span><input required minLength={2} value={draft.name} onChange={e => setDraft({...draft,name:e.target.value})} /></label><label className="field"><span>Categoria</span><input value={draft.category??''} onChange={e => setDraft({...draft,category:e.target.value})} /></label>{(['sale_price_cents','cost_cents','minimum_quantity'] as const).map(k => <label className="field" key={k}><span>{{sale_price_cents:'Venda (R$)',cost_cents:'Custo (R$)',minimum_quantity:'Estoque mínimo'}[k]}</span><input type="number" required min="0" step={k==='minimum_quantity'?1:0.01} value={draft[k]/(k==='minimum_quantity'?1:100)} onChange={e => setDraft({...draft,[k]:Math.round(Number(e.target.value)*(k==='minimum_quantity'?1:100))})} /></label>)}<label className="check"><input type="checkbox" checked={draft.active} onChange={e => setDraft({...draft,active:e.target.checked})} /> Ativo</label>{error && <p className="form-error">{error}</p>}<button className="primary" disabled={busy}>Salvar produto</button></form></Modal>}
    {stock && <Modal title={`Estoque · ${stock.name}`} close={() => setStock(null)}><form onSubmit={async e => { e.preventDefault(); if(await run('adjust_stock',{id:stock.id,delta:Number(delta),notes})) setStock(null) }}><label className="field"><span>Quantidade a adicionar ou retirar (ex.: 5 ou -2)</span><input required type="number" step="1" value={delta} onChange={e => setDelta(e.target.value)} /></label><label className="field"><span>Motivo</span><input required minLength={3} value={notes} onChange={e => setNotes(e.target.value)} /></label>{error && <p className="form-error">{error}</p>}<button className="primary" disabled={busy}>Registrar ajuste</button></form></Modal>}
  </Page>
}
