import { useState, type ReactNode } from 'react'
import { Link } from 'react-router-dom'
import { useOperations } from './OperationsStore'
import { useCatalog } from './CatalogStore'
import { cashBalance, commandTotal, dateTime, dayKey, exportCsv, labels, methods, money, summarize, type Appointment, type Customer, type Product } from './operations'
import { uploadCatalogPhoto } from './media'

export function Page({ title, text, action, children }: { title: string; text?: string; action?: ReactNode; children: ReactNode }) {
  return <section className="page"><div className="page-head"><div><h2>{title}</h2>{text && <p>{text}</p>}</div>{action}</div>{children}</section>
}
export function Modal({ title, close, children }: { title: string; close: () => void; children: ReactNode }) {
  return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label={title}><div className="modal-head"><h2>{title}</h2><button className="outline small" onClick={close}>Fechar</button></div>{children}</section></div>
}
function Metrics({ entries }: { entries: [string, string | number][] }) { return <div className="stats-grid">{entries.map(([label, value]) => <article className="stat-card" key={label}><span>{label}</span><strong>{value}</strong></article>)}</div> }
function Method({ value, set }: { value: string; set: (v: string) => void }) { return <label className="field"><span>Forma de pagamento</span><select value={value} onChange={e => set(e.target.value)}>{Object.entries(methods).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label> }
function Empty({ children = 'Nenhum registro neste período.' }: { children?: ReactNode }) { return <p className="empty">{children}</p> }
export function AppointmentIdentity({ appointment: a }: { appointment: Appointment }) {
  return <div className="appointment-identity"><strong>{a.customer_name} <span className="professional-label">· {a.professional_name}</span></strong><span>{a.service_name} · {money(a.expected_price_cents)}</span><small>{dateTime(a.starts_at)} · {labels[a.status] ?? a.status}</small></div>
}

export function Dashboard() {
  const { data } = useOperations(); const today = dayKey(); const summary = summarize(data, today, today)
  const pending = data.commissions.filter(c => c.status === 'pending').reduce((s, c) => s + c.commission_cents, 0)
  return <Page title="Visão geral" text="Dados reais da barbearia, atualizados automaticamente.">
    <Metrics entries={[["Agendamentos hoje", summary.appointments.length], ['Recebido hoje', money(summary.received)], ['Atendimentos concluídos hoje', summary.completed.length], ['Repasses pendentes', money(pending)]]} />
    <div className="management-grid"><section className="panel operation-panel"><div className="panel-title"><h3>Agenda de hoje</h3><Link to="/admin/agenda">Abrir agenda</Link></div>{summary.appointments.map(a => <div className="record-row" key={a.id}><AppointmentIdentity appointment={a} /></div>)}{!summary.appointments.length && <Empty />}</section>
    <section className="panel operation-panel"><h3>Estoque baixo</h3>{data.products.filter(p => p.active && p.quantity <= p.minimum_quantity).map(p => <p key={p.id}>{p.name} · {p.quantity} un.</p>)}{!data.products.some(p => p.active && p.quantity <= p.minimum_quantity) && <Empty>Sem produtos abaixo do mínimo.</Empty>}</section></div>
  </Page>
}

export function AppointmentModal({ close }: { close: () => void }) {
  const { services, professionals } = useCatalog(); const { run, busy, error } = useOperations()
  const [name, setName] = useState(''); const [phone, setPhone] = useState(''); const [service, setService] = useState(services.find(s => s.ativo)?.id ?? ''); const [professional, setProfessional] = useState(professionals.find(p => p.ativo)?.id ?? '')
  const [date, setDate] = useState(dayKey()); const [time, setTime] = useState('09:00'); const [price, setPrice] = useState(String(services.find(s => s.id === service)?.preco ?? 0))
  return <Modal title="Novo agendamento" close={close}><form onSubmit={async e => { e.preventDefault(); if (await run('create_appointment', { name, phone, professional_id: professional, service_id: service, starts_at: `${date}T${time}:00-03:00`, amount: Math.round(Number(price) * 100) })) close() }}><div className="form-grid">
    <label className="field"><span>Cliente</span><input required minLength={2} value={name} onChange={e => setName(e.target.value)} /></label><label className="field"><span>WhatsApp</span><input required type="tel" minLength={10} value={phone} onChange={e => setPhone(e.target.value)} /></label>
    <label className="field"><span>Profissional</span><select required value={professional} onChange={e => setProfessional(e.target.value)}><option value="">Selecione</option>{professionals.filter(p => p.ativo).map(p => <option value={p.id} key={p.id}>{p.nome}</option>)}</select></label>
    <label className="field"><span>Serviço</span><select required value={service} onChange={e => { setService(e.target.value); setPrice(String(services.find(s => s.id === e.target.value)?.preco ?? 0)) }}><option value="">Selecione</option>{services.filter(s => s.ativo).map(s => <option value={s.id} key={s.id}>{s.nome}</option>)}</select></label>
    <label className="field"><span>Data</span><input type="date" required value={date} onChange={e => setDate(e.target.value)} /></label><label className="field"><span>Hora</span><input type="time" required value={time} onChange={e => setTime(e.target.value)} /></label><label className="field"><span>Valor (R$)</span><input required type="number" min="0" step="0.01" value={price} onChange={e => setPrice(e.target.value)} /></label></div>
    {error && <p role="alert" className="form-error">{error}</p>}<button disabled={busy} className="primary">{busy ? 'Salvando…' : 'Salvar agendamento'}</button></form></Modal>
}

export function Agenda({ onNew }: { onNew: () => void }) {
  const { data, run, busy, error } = useOperations(); const { professionals } = useCatalog()
  const [date, setDate] = useState(dayKey()); const [professional, setProfessional] = useState(''); const [search, setSearch] = useState(''); const [all, setAll] = useState(false)
  const [filtersOpen, setFiltersOpen] = useState(false)
  const [confirmation, setConfirmation] = useState<{ appointment: Appointment; status: string } | null>(null)
  const [removing, setRemoving] = useState<Appointment | null>(null)
  const [actualPrice, setActualPrice] = useState('')
  const rows = data.appointments.filter(a => a.status !== 'cancelled' && (all || dayKey(a.starts_at) === date) && (!professional || a.professional_id === professional) && `${a.customer_name} ${a.professional_name} ${a.service_name}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()))
  return <Page title="Agenda" text="Confirme somente se o cliente veio ou não veio." action={<div className="row-actions"><button className="outline" onClick={() => setFiltersOpen(value => !value)}>{filtersOpen ? 'Fechar filtros' : 'Filtros'}</button><button className="primary" onClick={onNew}>Novo agendamento</button></div>}>
    {filtersOpen && <div className="management-filters filter-panel"><label>Data<input type="date" value={date} onChange={e => { setDate(e.target.value); setAll(false) }} /></label><label>Profissional<select value={professional} onChange={e => setProfessional(e.target.value)}><option value="">Todos</option>{professionals.map(p => <option key={p.id} value={p.id}>{p.nome}</option>)}</select></label><label>Buscar<input placeholder="Cliente, profissional ou serviço" value={search} onChange={e => setSearch(e.target.value)} /></label><label className="check"><input type="checkbox" checked={all} onChange={e => setAll(e.target.checked)} /> Todas as datas</label></div>}
    <section className="panel operation-panel">{rows.map(a => <article className="record-row" key={a.id}><AppointmentIdentity appointment={a} /><div className="row-actions">{!['completed','cancelled','no_show'].includes(a.status) && <>
      <button className="primary small" disabled={busy} onClick={() => { setActualPrice(String(a.expected_price_cents / 100)); setConfirmation({ appointment: a, status: 'completed' }) }}>Compareceu</button><button className="outline small" disabled={busy} onClick={() => setConfirmation({ appointment: a, status: 'no_show' })}>Não compareceu</button><button className="text-button" disabled={busy} onClick={() => setRemoving(a)}>Remover</button>
    </>}</div></article>)}{!rows.length && <Empty />}</section>
    {confirmation && <Modal title={confirmation.status === 'completed' ? 'Cliente compareceu?' : 'Cliente não compareceu?'} close={() => setConfirmation(null)}><AppointmentIdentity appointment={confirmation.appointment} /><p>{confirmation.status === 'completed' ? 'O atendimento ficará pronto para receber no Caixa.' : 'O horário será marcado como não compareceu.'}</p>{confirmation.status === 'completed' && confirmation.appointment.expected_price_cents <= 0 && <label className="field"><span>Valor cobrado (R$)</span><input autoFocus required type="number" min="0.01" step="0.01" value={actualPrice} onChange={e => setActualPrice(e.target.value)} /></label>}{error && <p className="form-error">{error}</p>}<button className="primary" disabled={busy} onClick={async () => { if (confirmation.status === 'completed' && confirmation.appointment.expected_price_cents <= 0 && !(await run('set_price', { id: confirmation.appointment.id, amount: Math.round(Number(actualPrice) * 100) }))) return; if (await run('set_status', { id: confirmation.appointment.id, status: confirmation.status })) setConfirmation(null) }}>Confirmar</button></Modal>}
    {removing && <Modal title="Remover agendamento" close={() => setRemoving(null)}><AppointmentIdentity appointment={removing}/><p>Esse horário será removido da agenda. O histórico financeiro permanece protegido.</p>{error && <p className="form-error">{error}</p>}<button className="danger" disabled={busy} onClick={async()=>{if(await run('set_status',{id:removing.id,status:'cancelled'}))setRemoving(null)}}>Remover da agenda</button></Modal>}
  </Page>
}

export function Customers() {
  const { data, run, busy, error } = useOperations(); const [search, setSearch] = useState(''); const [draft, setDraft] = useState<Customer | null>(null); const [history, setHistory] = useState<string | null>(null)
  const visible = data.customers.filter(c => `${c.name} ${c.phone}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()))
  const remove = async () => { if (!draft?.id || !window.confirm('Remover este cliente? Primeiro remova os agendamentos dele, se houver.')) return; if (await run('delete_customer',{ id:draft.id })) setDraft(null) }
  return <Page title="Clientes" text="Clientes do agendamento e histórico de atendimentos." action={<button className="primary" onClick={() => setDraft({ id: '', name: '', phone: '', notes: '' })}>Novo cliente</button>}>
    <div className="management-filters"><label>Buscar cliente<input value={search} onChange={e => setSearch(e.target.value)} placeholder="Nome ou telefone" /></label></div><section className="panel operation-panel">{visible.map(c => {
      const visits = data.appointments.filter(a => a.customer_id === c.id && a.status === 'completed'); const commands = new Set(data.commands.filter(cmd => cmd.customer_id === c.id).map(cmd => cmd.id)); const paid = data.payments.filter(p => commands.has(p.command_id) && !p.reversed_at).reduce((s, p) => s + p.amount_cents, 0)
      return <div className="record-row" key={c.id}><div><strong>{c.name}</strong><p>{c.phone} · {visits.length} visitas · {money(paid)} pagos</p></div><div className="row-actions"><button className="outline small" onClick={() => setHistory(c.id)}>Histórico</button><button className="outline small" onClick={() => setDraft({ ...c })}>Editar</button></div></div>
    })}{!visible.length && <Empty />}</section>
    {draft && <Modal title={draft.id ? 'Editar cliente' : 'Novo cliente'} close={() => setDraft(null)}><form onSubmit={async e => { e.preventDefault(); if (await run('save_customer', { ...draft, id: draft.id || null })) setDraft(null) }}><label className="field"><span>Nome</span><input required minLength={2} value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} /></label><label className="field"><span>Telefone</span><input required type="tel" minLength={10} value={draft.phone} onChange={e => setDraft({ ...draft, phone: e.target.value })} /></label><label className="field"><span>Observações</span><textarea value={draft.notes ?? ''} onChange={e => setDraft({ ...draft, notes: e.target.value })} /></label>{error && <p className="form-error">{error}</p>}<div className="row-actions"><button className="primary" disabled={busy}>Salvar cliente</button>{draft.id && <button className="danger-button" type="button" disabled={busy} onClick={()=>void remove()}>Excluir cliente</button>}</div></form></Modal>}
    {history && <Modal title="Histórico do cliente" close={() => setHistory(null)}>{data.appointments.filter(a => a.customer_id === history).map(a => <div className="record-row" key={a.id}><AppointmentIdentity appointment={a} /></div>)}{!data.appointments.some(a => a.customer_id === history) && <Empty />}</Modal>}
  </Page>
}

export function Orders({ onNew }: { onNew: () => void }) {
  const { data, run, busy, error } = useOperations(); const [filter, setFilter] = useState(''); const [receive, setReceive] = useState(''); const [method, setMethod] = useState('pix'); const [priceId, setPriceId] = useState(''); const [price, setPrice] = useState('')
  const selected = data.commands.find(c => c.id === receive)
  return <Page title="Comandas" text="Cada agendamento abre uma comanda. Conclua o atendimento e registre o recebimento." action={<button className="primary" onClick={onNew}>Nova comanda</button>}>
    <div className="management-filters"><label>Situação<select value={filter} onChange={e => setFilter(e.target.value)}><option value="">Todas</option>{['open','awaiting_payment','closed','voided'].map(s => <option key={s} value={s}>{labels[s]}</option>)}</select></label></div>
    <section className="panel operation-panel">{data.commands.filter(c => !filter || c.status === filter).map(c => { const a = data.appointments.find(a => a.id === c.appointment_id); return <div className="record-row" key={c.id}><div>{a ? <AppointmentIdentity appointment={a} /> : <strong>{data.customers.find(x => x.id === c.customer_id)?.name ?? 'Cliente'}</strong>}<p>{labels[c.status]} · Total: {money(commandTotal(data, c))}</p>{data.payments.filter(p => p.command_id === c.id && !p.reversed_at).map(p => <small key={p.id}>Recebido: {money(p.amount_cents)} · {methods[p.method]} · {dateTime(p.paid_at)}</small>)}</div><div className="row-actions">{c.status === 'open' && a && <><button className="outline small" onClick={() => { setPriceId(a.id); setPrice(String(a.expected_price_cents / 100)) }}>Alterar valor</button><Link className="outline small" to="/admin/agenda">Confirmar realização na agenda</Link></>}{c.status === 'awaiting_payment' && <button className="primary small" onClick={() => setReceive(c.id)}>Registrar recebimento</button>}</div></div> })}{!data.commands.some(c => !filter || c.status === filter) && <Empty />}</section>
    {selected && <Modal title="Registrar recebimento" close={() => setReceive('')}><p>Total: <strong>{money(commandTotal(data, selected))}</strong></p><Method value={method} set={setMethod} /><p>Confirme somente depois de receber do cliente. O registro entrará no caixa aberto.</p>{error && <p className="form-error">{error}</p>}<button className="primary" disabled={busy} onClick={async () => { if (await run('receive', { id: receive, method })) setReceive('') }}>Confirmar pagamento recebido</button></Modal>}
    {priceId && <Modal title="Valor do atendimento" close={() => setPriceId('')}><form onSubmit={async e => { e.preventDefault(); if (await run('set_price', { id: priceId, amount: Math.round(Number(price)*100) })) setPriceId('') }}><label className="field"><span>Valor (R$)</span><input required type="number" min="0.01" step="0.01" value={price} onChange={e => setPrice(e.target.value)} /></label>{error && <p className="form-error">{error}</p>}<button className="primary" disabled={busy}>Salvar valor</button></form></Modal>}
  </Page>
}

export function CashManagement() {
  const { data, run, busy, error } = useOperations(); const { professionals } = useCatalog()
  const [dialog, setDialog] = useState(''); const [amount, setAmount] = useState(''); const [notes, setNotes] = useState(''); const [method, setMethod] = useState('cash'); const [type, setType] = useState('expense'); const [professionalId, setProfessionalId] = useState(''); const [entryIds, setEntryIds] = useState<string[]>([]); const [receive, setReceive] = useState(''); const [filtersOpen,setFiltersOpen]=useState(false); const [commissionView,setCommissionView]=useState('pending'); const [commissionProfessional,setCommissionProfessional]=useState('')
  const active = data.sessions.find(s => !s.closed_at); const [chosenSession, setChosenSession] = useState(''); const shown = data.sessions.find(s => s.id === chosenSession) ?? active ?? data.sessions[0]
  const pending = data.commissions.filter(e => e.status === 'pending' && e.commission_cents > 0)
  const movements = data.movements.filter(m => m.session_id === shown?.id)
  const pendingPayments = data.commands.filter(c => c.status === 'awaiting_payment')
  const payment = data.commands.find(c => c.id === receive)
  const openDialog = (value: string) => { setDialog(value); setAmount(''); setNotes(''); setMethod('cash') }
  const submit = async (e: React.FormEvent) => {
    e.preventDefault()
    const action = dialog === 'open' ? 'open_cash' : dialog === 'close' ? 'close_cash' : dialog === 'pay' ? 'pay_commissions' : 'move_cash'
    if (await run(action, { id: dialog === 'pay' ? professionalId : active?.id, amount: Math.round(Number(amount)*100), method, type, notes, entries: entryIds })) setDialog('')
  }
  const visibleCommissions=data.commissions.filter(e=>e.commission_cents>0&&e.status===commissionView&&(!commissionProfessional||e.professional_id===commissionProfessional))
  return <Page title="Caixa" text="Controle de recebimentos e repasses." action={<div className="row-actions"><button className="outline" onClick={()=>setFiltersOpen(v=>!v)}>{filtersOpen?'Fechar filtros':'Filtros'}</button><button className="primary" disabled={busy} onClick={() => openDialog(active ? 'close' : 'open')}>{active ? 'Fechar caixa' : 'Abrir caixa'}</button></div>}>
    {filtersOpen&&<div className="management-filters filter-panel"><label>Caixa<select value={shown?.id ?? ''} onChange={e => setChosenSession(e.target.value)}>{!data.sessions.length && <option value="">Nenhum caixa aberto</option>}{data.sessions.map(s => <option key={s.id} value={s.id}>{dateTime(s.opened_at)} · {s.closed_at ? 'Fechado' : 'Aberto'}</option>)}</select></label><label>Repasses<select value={commissionView} onChange={e=>setCommissionView(e.target.value)}><option value="pending">Pendentes</option><option value="paid">Pagos</option></select></label><label>Profissional<select value={commissionProfessional} onChange={e=>setCommissionProfessional(e.target.value)}><option value="">Todos</option>{professionals.map(p=><option value={p.id} key={p.id}>{p.nome}</option>)}</select></label></div>}
    <Metrics entries={[["Caixa", active ? 'Aberto' : 'Fechado'], ['Saldo previsto', money(shown ? cashBalance(data, shown) : 0)], ['Para receber', money(pendingPayments.reduce((s,c)=>s+commandTotal(data,c),0))], ['Repasses pendentes', money(pending.reduce((s,e) => s+e.commission_cents,0))]]} />
    <section className="panel operation-panel"><h3>Prontos para receber</h3>{pendingPayments.map(command => { const appointment = data.appointments.find(a => a.id === command.appointment_id); return <div className="record-row" key={command.id}><div>{appointment && <AppointmentIdentity appointment={appointment} />}<strong>Total: {money(commandTotal(data, command))}</strong></div><button className="primary small" disabled={!active || busy} onClick={() => { setMethod('pix'); setReceive(command.id) }}>Confirmar pagamento</button></div> })}{!pendingPayments.length && <Empty>Nenhum pagamento aguardando confirmação.</Empty>}</section>
    <section className="panel operation-panel"><div className="panel-title"><h3>Movimentações</h3><button className="outline small" disabled={!active || busy} onClick={() => openDialog('move')}>Novo lançamento</button></div>
    {shown?.closed_at && <p>Contado: {money(shown.declared_balance_cents ?? 0)} · Diferença: {money((shown.declared_balance_cents ?? 0)-cashBalance(data, shown))}</p>}
    {movements.map(m => { const cmd = data.commands.find(c => c.id === m.command_id); const a = data.appointments.find(a => a.id === cmd?.appointment_id); return <div className="record-row" key={m.id}><div><strong>{m.notes}</strong><p>{a ? `${a.customer_name} · ${a.professional_name} · ${a.service_name}` : ''}</p><small>{dateTime(m.created_at)} · {methods[m.payment_method]}</small></div><strong className={m.amount_cents < 0 ? 'red' : 'green'}>{money(m.amount_cents)}</strong></div> })}{!movements.length && <Empty />}</section>
    <section className="panel operation-panel"><h3>{commissionView==='pending'?'Repasses pendentes':'Repasses pagos'}</h3>{commissionView==='pending'?[...new Set(visibleCommissions.map(e=>e.professional_id))].map(id => { const entries = visibleCommissions.filter(e => e.professional_id === id); return <div className="record-row" key={id}><strong>{professionals.find(p => p.id === id)?.nome ?? data.appointments.find(a => a.professional_id === id)?.professional_name ?? 'Profissional'}</strong><span>{entries.length} serviços · {money(entries.reduce((s,e) => s+e.commission_cents,0))}</span><button className="primary small" disabled={!active || busy} onClick={() => { setProfessionalId(id); setEntryIds(entries.map(e => e.id)); openDialog('pay') }}>Pagar repasse</button></div> }):visibleCommissions.map(e=><div className="record-row" key={e.id}><span>{professionals.find(p=>p.id===e.professional_id)?.nome??'Profissional'} · {e.paid_at?dateTime(e.paid_at):''}</span><strong>{money(e.commission_cents)}</strong></div>)}{!visibleCommissions.length&&<Empty>{commissionView==='pending'?'Nenhum repasse pendente.':'Nenhum repasse pago neste filtro.'}</Empty>}</section>
    {dialog && <Modal title={{ open: 'Abrir caixa', close: 'Fechar caixa', move: 'Novo lançamento', pay: 'Registrar repasse' }[dialog] ?? ''} close={() => setDialog('')}><form onSubmit={submit}>
      {dialog === 'pay' ? <p>Confirmar o pagamento de {money(pending.filter(e => entryIds.includes(e.id)).reduce((s,e) => s+e.commission_cents,0))} ao profissional?</p> : <label className="field"><span>{dialog === 'open' ? 'Dinheiro inicial (R$)' : dialog === 'close' ? 'Dinheiro contado no fechamento (R$)' : 'Valor (R$)'}</span><input autoFocus required type="number" min={dialog === 'move' ? '0.01' : '0'} step="0.01" value={amount} onChange={e => setAmount(e.target.value)} /></label>}
      {dialog === 'move' && <label className="field"><span>Tipo</span><select value={type} onChange={e => setType(e.target.value)}><option value="expense">Despesa</option><option value="withdrawal">Retirada</option><option value="reinforcement">Reforço</option></select></label>}
      {['pay','move'].includes(dialog) && <Method value={method} set={setMethod} />}{['close','move'].includes(dialog) && <label className="field"><span>Descrição / observação</span><input required={dialog === 'move'} minLength={dialog === 'move' ? 3 : undefined} value={notes} onChange={e => setNotes(e.target.value)} /></label>}
      {dialog === 'close' && active && <p>Dinheiro esperado: {money(cashBalance(data, active))}. Pix e cartões ficam separados do dinheiro físico.</p>}{error && <p className="form-error">{error}</p>}<button className="primary" disabled={busy}>Confirmar</button></form></Modal>}
    {payment && <Modal title="Confirmar pagamento" close={() => setReceive('')}><p>Total: <strong>{money(commandTotal(data, payment))}</strong></p><Method value={method} set={setMethod} />{error && <p className="form-error">{error}</p>}<button className="primary" disabled={busy || !active} onClick={async () => { if (await run('receive', { id: payment.id, method })) setReceive('') }}>Pagamento recebido</button></Modal>}
  </Page>
}

export function Reports() {
  const { data } = useOperations(); const { professionals } = useCatalog(); const [from, setFrom] = useState(dayKey().slice(0,7)+'-01'); const [to, setTo] = useState(dayKey()); const [professional, setProfessional] = useState(''); const [filtersOpen,setFiltersOpen]=useState(false)
  const summary = summarize(data, from, to, professional)
  const expenses = data.movements.filter(m => m.type==='expense' && dayKey(m.created_at)>=from && dayKey(m.created_at)<=to).reduce((s,m) => s-m.amount_cents,0)
  const ids = [...new Set(summary.completed.map(a => a.professional_id))]
  const exportRows = () => exportCsv(`relatorio-${from}-${to}.csv`, [['Cliente','Profissional','Serviço','Data','Status','Valor (R$)'], ...summary.appointments.map(a => [a.customer_name,a.professional_name,a.service_name,dateTime(a.starts_at),labels[a.status],(a.expected_price_cents/100).toFixed(2)])])
  return <Page title="Relatórios" text="Resumo simples da operação." action={<div className="row-actions"><button className="outline" onClick={()=>setFiltersOpen(v=>!v)}>{filtersOpen?'Fechar filtros':'Filtros'}</button><button className="outline" onClick={exportRows}>Exportar CSV</button></div>}>
    {filtersOpen&&<div className="management-filters filter-panel"><label>De<input type="date" value={from} onChange={e => setFrom(e.target.value)} /></label><label>Até<input type="date" min={from} value={to} onChange={e => setTo(e.target.value)} /></label><label>Profissional<select value={professional} onChange={e => setProfessional(e.target.value)}><option value="">Todos</option>{professionals.map(p => <option key={p.id} value={p.id}>{p.nome}</option>)}</select></label></div>}
    <Metrics entries={[["Faturamento", money(summary.gross)], ['Recebido', money(summary.received)], ['A repassar', money(summary.pending)], ['Resultado', money(summary.shop-expenses)]]} />
    <section className="panel operation-panel"><h3>Por profissional</h3>{ids.map(id => { const s = summarize(data, from, to, id); return <div className="record-row" key={id}><strong>{summary.completed.find(a => a.professional_id === id)?.professional_name}</strong><span>{s.completed.length} atendimentos · {money(s.gross)}</span><span>Comissão: {money(s.earned)}</span></div> })}{!ids.length && <Empty />}</section>
    <section className="panel operation-panel"><h3>Atendimentos no período</h3>{summary.appointments.map(a => <div className="record-row" key={a.id}><AppointmentIdentity appointment={a} /></div>)}{!summary.appointments.length && <Empty />}</section>
  </Page>
}

export function Products() {
  const { data, run, busy, error } = useOperations(); const [draft, setDraft] = useState<Product | null>(null); const [stock, setStock] = useState<Product | null>(null); const [photo,setPhoto]=useState<File|null>(null); const [delta,setDelta] = useState(''); const [notes,setNotes] = useState('')
  const fresh: Product = { id:'',name:'',category:'',quantity:0,minimum_quantity:0,sale_price_cents:0,cost_cents:0,active:true,photo_url:null }
  return <Page title="Produtos e estoque" text="Cadastros e movimentações salvos no sistema." action={<button className="primary" onClick={() => {setDraft(fresh);setPhoto(null)}}>Novo produto</button>}><section className="product-grid">{data.products.map(p => <article className="product-card" key={p.id}>{p.photo_url?<img className="product-photo" src={p.photo_url} alt=""/>:<div className="product-photo product-placeholder">Produto</div>}<div className="product-card-body"><strong>{p.name}</strong><p>{p.category || 'Sem categoria'} · {money(p.sale_price_cents)}</p><span className={p.quantity<=p.minimum_quantity ? 'low' : ''}>{p.quantity} un. · mín. {p.minimum_quantity}</span><div className="row-actions"><button className="outline small" onClick={() => {setDraft({ ...p });setPhoto(null)}}>Editar</button><button className="outline small" onClick={() => { setStock(p); setDelta(''); setNotes('') }}>Estoque</button></div></div></article>)}{!data.products.length && <section className="panel operation-panel"><Empty /></section>}</section>
    {draft && <Modal title="Produto" close={() => setDraft(null)}><form onSubmit={async e => { e.preventDefault(); try {let photoUrl=draft.photo_url??null;if(photo)photoUrl=await uploadCatalogPhoto(photo,'products');if (await run('save_product_profile', { id:draft.id||null,name:draft.name,category:draft.category,price:draft.sale_price_cents,cost:draft.cost_cents,minimum:draft.minimum_quantity,active:draft.active,photo_url:photoUrl })) setDraft(null)} catch(err) { alert(err instanceof Error?err.message:'Não foi possível enviar a foto.') } }}><label className="field"><span>Foto (4:5)</span><input accept="image/*" type="file" onChange={e=>setPhoto(e.target.files?.[0]??null)}/></label>{draft.photo_url&&!photo&&<img className="photo-preview" src={draft.photo_url} alt=""/>}<label className="field"><span>Nome</span><input required minLength={2} value={draft.name} onChange={e => setDraft({...draft,name:e.target.value})} /></label><label className="field"><span>Categoria</span><input value={draft.category??''} onChange={e => setDraft({...draft,category:e.target.value})} /></label>{(['sale_price_cents','cost_cents','minimum_quantity'] as const).map(k => <label className="field" key={k}><span>{{sale_price_cents:'Venda (R$)',cost_cents:'Custo (R$)',minimum_quantity:'Estoque mínimo'}[k]}</span><input type="number" required min="0" step={k==='minimum_quantity'?1:0.01} value={draft[k]/(k==='minimum_quantity'?1:100)} onChange={e => setDraft({...draft,[k]:Math.round(Number(e.target.value)*(k==='minimum_quantity'?1:100))})} /></label>)}<label className="check"><input type="checkbox" checked={draft.active} onChange={e => setDraft({...draft,active:e.target.checked})} /> Ativo</label>{error && <p className="form-error">{error}</p>}<button className="primary" disabled={busy}>Salvar produto</button></form></Modal>}
    {stock && <Modal title={`Estoque · ${stock.name}`} close={() => setStock(null)}><form onSubmit={async e => { e.preventDefault(); if(await run('adjust_stock',{id:stock.id,delta:Number(delta),notes})) setStock(null) }}><label className="field"><span>Quantidade a adicionar ou retirar (ex.: 5 ou -2)</span><input required type="number" step="1" value={delta} onChange={e => setDelta(e.target.value)} /></label><label className="field"><span>Motivo</span><input required minLength={3} value={notes} onChange={e => setNotes(e.target.value)} /></label>{error && <p className="form-error">{error}</p>}<button className="primary" disabled={busy}>Registrar ajuste</button></form></Modal>}
  </Page>
}
