import { useState } from 'react'
import { useCatalog } from './CatalogStore'
import { type Servico, type Profissional } from './data'
import { Page, Modal } from './ManagementPages'
import { money } from './operations'

export function ServicesV2(){
  const {services,updateService,addService}=useCatalog()
  const [draft,setDraft]=useState<Servico|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false)
  const fresh:Servico={id:'',nome:'',descricao:'',preco:0,duracao:30,cor:'#203F20',ativo:true}
  return <Page title="Serviços" text="Preços e duração usados no agendamento público." action={<button className="primary" onClick={()=>{setDraft(fresh);setError('')}}>Novo serviço</button>}><section className="panel operation-panel">{services.map(s=><div className="record-row" key={s.id}><div><strong>{s.nome}</strong><p>{s.duracao} min · {money(s.preco*100)} · {s.ativo?'Ativo':'Pausado'}</p></div><button className="outline small" aria-label={`Editar ${s.nome}`} onClick={()=>{setDraft({...s});setError('')}}>Editar</button></div>)}{!services.length&&<p className="empty">Nenhum serviço cadastrado.</p>}</section>
  {draft&&<Modal title={draft.id?'Editar serviço':'Novo serviço'} close={()=>setDraft(null)}><form onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{const err=await(draft.id?updateService(draft.id,draft):addService(draft));if(err)setError(err);else setDraft(null)}finally{setBusy(false)}}}><label className="field"><span>Nome</span><input required minLength={2} value={draft.nome} onChange={e=>setDraft({...draft,nome:e.target.value})}/></label><label className="field"><span>Descrição</span><input value={draft.descricao} onChange={e=>setDraft({...draft,descricao:e.target.value})}/></label><label className="field"><span>Preço (R$)</span><input required type="number" min="0" step="0.01" value={draft.preco} onChange={e=>setDraft({...draft,preco:Number(e.target.value)})}/></label><label className="field"><span>Duração (minutos)</span><input required type="number" min="5" max="480" value={draft.duracao} onChange={e=>setDraft({...draft,duracao:Number(e.target.value)})}/></label><label className="check"><input type="checkbox" checked={draft.ativo} onChange={e=>setDraft({...draft,ativo:e.target.checked})}/>Disponível para agendamento</label>{error&&<p className="form-error">{error}</p>}<button className="primary" disabled={busy}>{busy?'Salvando…':'Salvar serviço'}</button></form></Modal>}</Page>
}
export function ProfessionalsV2(){
  const {professionals,updateProfessional,addProfessional,deleteProfessional}=useCatalog()
  const [draft,setDraft]=useState<Profissional|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false)
  const fresh:Profissional={id:'',nome:'',telefone:'',especialidades:'',comissao:40,iniciais:'',cor:'#203F20',ativo:true}
  const remove=async()=>{if(!draft||busy||!window.confirm('Remover este profissional do agendamento? O histórico será preservado.'))return;setBusy(true);try{const err=await deleteProfessional(draft.id);if(err)setError(err);else setDraft(null)}finally{setBusy(false)}}
  return <Page title="Profissionais" text="Profissionais ativos aparecem automaticamente no agendamento." action={<button className="primary" onClick={()=>{setDraft(fresh);setError('')}}>Novo profissional</button>}><section className="panel operation-panel">{professionals.map(p=><div className="record-row" key={p.id}><div><strong>{p.nome}</strong><p>{p.especialidades} · {p.ativo?'Ativo':'Inativo'} · {p.nome.trim().toLocaleLowerCase()==='machado'?'100% para a barbearia':'40% de comissão'}</p></div><button className="outline small" onClick={()=>{setDraft({...p});setError('')}}>Editar</button></div>)}{!professionals.length&&<p className="empty">Nenhum profissional cadastrado.</p>}</section>
  {draft&&<Modal title={draft.id?'Editar profissional':'Novo profissional'} close={()=>setDraft(null)}><form onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{const err=await(draft.id?updateProfessional(draft.id,draft):addProfessional(draft));if(err)setError(err);else setDraft(null)}finally{setBusy(false)}}}><label className="field"><span>Nome</span><input required minLength={2} value={draft.nome} onChange={e=>setDraft({...draft,nome:e.target.value})}/></label><label className="field"><span>Telefone</span><input type="tel" value={draft.telefone} onChange={e=>setDraft({...draft,telefone:e.target.value})}/></label><label className="field"><span>Especialidades</span><input value={draft.especialidades} onChange={e=>setDraft({...draft,especialidades:e.target.value})}/></label><label className="check"><input type="checkbox" checked={draft.ativo} onChange={e=>setDraft({...draft,ativo:e.target.checked})}/>Ativo no agendamento</label><p>Machado: todo o valor para a barbearia. Demais: 40% para o profissional e 60% para a barbearia.</p>{error&&<p className="form-error">{error}</p>}<div className="row-actions"><button className="primary" disabled={busy}>{busy?'Salvando…':'Salvar profissional'}</button>{draft.id&&draft.ativo&&<button className="danger-button" type="button" disabled={busy} onClick={()=>void remove()}>Excluir profissional</button>}</div></form></Modal>}</Page>
}
